version = 0.1

[default.deploy.parameters]
stack_name = "underdog-coach"
resolve_s3 = true
s3_prefix = "underdog-coach"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BedrockModelId=\"arn:aws:bedrock:eu-central-1:705766749486:inference-profile/eu.anthropic.claude-sonnet-4-6\" ScenarioAgentRuntimeArn=\"arn:aws:bedrock-agentcore:eu-central-1:705766749486:runtime/scenario_agent-E5xxlM3HXT\""

[default.build.parameters]
cached = true
parallel = true
